replicaCount: 2
clusterName: demo
image:
  repository: public.ecr.aws/eks/aws-load-balancer-controller
  tag: v2.7.1
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: aws-load-balancer-controller
  automountServiceAccountToken: true